---
version: "3"

services:
  runlet:
    build: .
    environment:
      RUNLET_NATS_URL: nats://queue:4222
      RUNLET_LOG_LEVEL: debug
    volumes:
    - "/var/run/docker.sock:/var/run/docker.sock"
  queue:
    image: nats
    ports:
    - "4222:4222"
    - "5222:5222"
    - "6222:6222"
  store:
    image: postgres
    ports:
    - "5432:5432"
