---
version: "3"

services:
  runlet:
    image: ubuntu:18.04
    environment:
      RUNLET_NATS_URL: nats://queue:4222
      RUNLET_LOG_LEVEL: debug
    volumes:
    - "/var/run/docker.sock:/var/run/docker.sock"
    - "./runlet:/bin/runlet"
    command: /bin/runlet
  queue:
    image: nats
    ports:
    - "4222:4222"
    - "5222:5222"
    - "6222:6222"
  store:
    image: postgres
    ports:
    - "5432:5432"
    environment:
      POSTGRES_USER: runlet_test
      POSTGRES_PASSWORD: runlet_test
      POSTGRES_DB: runlet_test
    volumes:
    - "./dockerfiles/postgres/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d"
